debian_task:
  container:
    dockerfile: debian.dockerfile
  env:
    matrix:
      - TAG: v3.8.0
      - TAG: v3.7.5
  checkout_script:
    - git clone --depth 1 --branch $TAG https://github.com/python/cpython.git
  build_script: |
    cp Setup.local cpython/Modules/Setup.local
    cd cpython
    # Configure
    ./configure "LDFLAGS=-static -static-libgcc" "CPPFLAGS=-static" --disable-shared --enable-optimizations
    # Build
    make python
  test_script:
    - ./cpython/python -c "print(__import__('sys').builtin_module_names)"
    - ./cpython/python test-imports.py
  binary_artifacts:
    path: cpython/python
  library_artifacts:
    path: cpython/libpython*.a
