debian_task:
  container:
    dockerfile: debian.dockerfile
  env:
    matrix:
      - TAG: v3.8.1
      # - TAG: v3.7.5
  checkout_script:
    - git clone --depth 1 --branch $TAG https://github.com/python/cpython.git
  delete_disabled_module_tests_script:
    # These are the tests for modules included in PEP 594 ("Removing dead batteries")
    # that aren't native Python. These are also disabled in gen-setup.py.
    - cd cpython/Lib/test/ && rm test_spwd.py test_parser.py test_crypt.py test_ossaudiodev.py test_nis.py
  build_script: |
    cp Setup.local cpython/Modules/Setup.local
    cd cpython
    # Configure
    ./configure "LDFLAGS=-static -static-libgcc" "CPPFLAGS=-static" --disable-shared --enable-optimizations
    # Build
    make python platform
  bundle_script:
    - cpython/python build-std.py cpython
  minitest_script:
    - ./cpython/python -c "print(__import__('sys').builtin_module_names)"
    - ./cpython/python test-imports.py
  binary_artifacts:
    path: cpython/python
  library_artifacts:
    path: cpython/libpython*.a
  stdlib_artifacts:
    path: stdlib.zip
  fulltest_script:
    - cd cpython && ./python Tools/scripts/run_tests.py

modinfo_task:
  container:
    dockerfile: debian.dockerfile
  env:
    - TAG: v3.8.1
  checkout_script:
    - git clone --depth 1 --branch $TAG https://github.com/python/cpython.git
  build_script: |
    cd cpython
    # Configure
    ./configure "LDFLAGS=-static -static-libgcc" "CPPFLAGS=-static" --disable-shared --enable-optimizations
    # Build
    make python platform
  json_script:
    -  _PYTHON_PROJECT_BASE=$PWD/cpython ./cpython/python gen-info.py > mods.json
  setup_script:
    - apt-get install -y python3
    - python3 gen-setup.py < mods.json > mods.setup
  modinfo_artifacts:
    path: mods.*
