debian_task:
  container:
    dockerfile: debian.dockerfile
  env:
    matrix:
      - TAG: v3.8.0
      - TAG: v3.7.5
  checkout_script:
    - git clone --depth 1 --branch $TAG https://github.com/python/cpython.git
  build_script: |
    cp Setup.local cpython/Modules/Setup.local
    cd cpython
    # Configure
    ./configure "LDFLAGS=-static -static-libgcc" "CPPFLAGS=-static" --disable-shared --enable-optimizations
    # Build
    make python platform
  test_script:
    - ./cpython/python -c "print(__import__('sys').builtin_module_names)"
    - ./cpython/python test-imports.py
    - cd cpython && ./python Tools/scripts/run_tests.py
  binary_artifacts:
    path: cpython/python
  library_artifacts:
    path: cpython/libpython*.a

modinfo_task:
  container:
    dockerfile: debian.dockerfile
  env:
    - TAG: v3.8.0
  checkout_script:
    - git clone --depth 1 --branch $TAG https://github.com/python/cpython.git
  build_script: |
    cd cpython
    # Configure
    ./configure "LDFLAGS=-static -static-libgcc" "CPPFLAGS=-static" --disable-shared --enable-optimizations
    # Build
    make python platform
  gen_script:
    -  _PYTHON_PROJECT_BASE=$PWD/cpython ./cpython/python gen-info.py > mods.json
    - python3 gen-setup.py < mods.json > mods.setup
  modinfo_artifacts:
    path: mods.*
