debian_task:
  container:
    dockerfile: debian.dockerfile
  env:
    PYTHON_TAG: 3.8
  checkout_script:
    - git clone --depth 1 --branch $PYTHON_TAG https://github.com/python/cpython.git
  build_script: |
    cd cpython
    echo "*static*" > /tmp/setup
    cat Modules/Setup >> /tmp/setup
    cp /tmp/setup Modules/Setup
    ./configure "LDFLAGS=-static -static-libgcc" "CPPFLAGS=-static"
    make
  test_script:
    - ./cpython/python test-imports.py
  binary_artifacts:
    path: cpython/python
  library_artifacts:
    path: cpython/libpython*.a
