debian_task:
  container:
    dockerfile: debian.dockerfile
  env:
    matrix:
      - TAG: v3.8.0
      - TAG: v3.7.5
  checkout_script:
    - git clone --depth 1 --branch $TAG https://github.com/python/cpython.git
  build_script: |
    cd cpython
    # Prepend *static* to file
    echo "*static*" > /tmp/setup
    cat Modules/Setup* >> /tmp/setup
    cp /tmp/setup Modules/Setup
    # Configure
    ./configure "LDFLAGS=-static -static-libgcc" "CPPFLAGS=-static" --disable-shared
    # Build
    make "LDFLAGS=-static" "LINKFORSHARED= "
  test_script:
    - ./cpython/python -c "print(__import__('sys').builtin_module_names)"
    - ./cpython/python test-imports.py
  binary_artifacts:
    path: cpython/python
  library_artifacts:
    path: cpython/libpython*.a
