debian_task:
  container:
    dockerfile: debian.dockerfile
  env:
    # TODO: Matrix
    PYTHON_TAG: 3.8
  checkout_script:
    - git clone --depth 1 --branch $PYTHON_TAG https://github.com/python/cpython.git
  build_script: |
    cd cpython
    # Prepend *static* to file
    echo "*static*" > /tmp/setup
    cat Modules/Setup >> /tmp/setup
    cp /tmp/setup Modules/Setup
    # Configure
    ./configure "LDFLAGS=-static -static-libgcc" "CPPFLAGS=-static" --disable-shared
    # Build
    make "LDFLAGS=-static" "LINKFORSHARED= "
  test_script:
    - ./cpython/python test-imports.py
  binary_artifacts:
    path: cpython/python
  library_artifacts:
    path: cpython/libpython*.a
